### ISSUE TITLE
CancelBooking failing 50% of the time

### ISSUE THREAD

**Issue by lalo** [acmeair/acmeair-driver#3]
I'm playing around with the acmeair-driver and I'm seeing the following behaviour:

- around 50% of the calls to /cancelbooking fail
- fail with NullPointerException
- failing requests have missing POST data

Example of successful request:
```
POST http://40.86.208.15/booking/cancelbooking

POST data:
number=&userid=uid4%40email.com

Cookie Data:
jwt_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1aWQ0QGVtYWlsLmNvbSJ9.rTZyWUUi45DWVOo6RJ5OR-11x7xVEqoiW0OMuBszj2U; loggedinuser=uid4@email.com
```

Example of failing request:
```
POST http://40.86.208.15/booking/cancelbooking

POST data:


Cookie Data:
jwt_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1aWQxMTdAZW1haWwuY29tIn0.Gxl6tdZ91zlxS8mWTtExXKwzKsxpxrGbdgNQJpRWark; loggedinuser=uid117@email.com
```

This points to a possible bug on the driver which is triggering a cancel with bogus data (no POST data is propagated).

Have you seen this behaviour?

**Comment by lalo** [comment]
I'm actually using this fork https://github.com/blueperf/acmeair-driver

**Comment by yigitpolat** [comment]
Hello,

I also use the same fork above (https://github.com/blueperf/acmeair-driver) and still having the same issue which is around 50% of the calls to /cancelbooking fail. 

Any feedback about this?

**Comment by yigitpolat** [comment]
If you are generating load through the JMeter GUI, open the GUI with the below command and flag. Otherwise, you’ll need to reload the db every time.
```
./jmeter.sh -DusePureIDs=true
```
